### ISSUE TITLE
Error parsing JSON Feed

### ISSUE THREAD

**Issue by jsspalding** [fent/feedme.js#18]
The following error is occurring when trying to parse a JSON Feed.

Failing tested JSON Feeds:
https://daringfireball.net/feeds/json
http://inessential.com/feed.json

Error:
```
Exception has occurred: Error
TypeError: Cannot set property 'type' of undefined
    at CStream.parser.done (e:\Projects\ely\node_modules\feedme\lib\jsonfeedparser.js:140:15)
    at self.children.forEach (e:\Projects\ely\node_modules\eventyoshi\lib\index.js:255:28)
    at Map.forEach (native)
    at EventYoshi.Array.slice.call.forEach.self.(anonymous function) [as done] (e:\Projects\ely\node_modules\eventyoshi\lib\index.js:253:23)
    at EventYoshi.<anonymous> (e:\Projects\ely\feedparser.js:15:27)
    at emitNone (events.js:86:13)
    at EventYoshi.emit (events.js:185:7)
    at CStream.wrapper.__wrappers.(anonymous function) (e:\Projects\ely\node_modules\eventyoshi\lib\index.js:105:14)
    at emitNone (events.js:86:13)
    at CStream.emit (events.js:185:7)

```

This is the `e:\Projects\ely\feedparser.js`:
```
var FeedMe = require('feedme');
var Request = require('request');
var URL = require('url');

module.exports = function (url, cb) {

    var feedme = new FeedMe(true);

    feedme.on('error', function (error) {
        return cb(415);
    });

    feedme.on('end', function () {
        var feed = feedme.done();
        return cb(null, feed);
    });

    var options = {
        encoding: null,
        gzip: true,
        timeout: 5000,
        url: URL.parse(url)
    };

    Request.get(options, function(error, response, body) {
        if (error) {
            return cb(response.statusCode);
        } else {
            feedme.write(body);
            feedme.end();
        }
    })

};
```

**Comment by fent** [comment]
Ah, these feeds are using a new version of JSON feeds that was just released this year: https://jsonfeed.org/version/1

When I created this, that didn't exist. The JSON feed is instead an Atom feed, but in JSON format. I'll have to update this to use the new format, so I'll keep this opened.

**Comment by TheScree** [comment]
@fent Just as an FYI, Wordpress has a baked in JSON feed for all self-hosted installs. This is a MAJOR potential consumer of this. This not working is holding me back from using this library.

I ran into this issue attempting to consume a Wordpress JSON feed. As the owner of the Wordpress install, I can tell you that it's running the latest version as of today's date.

**Comment by jsspalding** [comment]
Thank you, @fent !

**Comment by TheScree** [comment]
Mucho Gracias ;)
