### ISSUE TITLE
possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by MichMich** [fent/feedme.js#8]
First of: awesome work! Really saved me a lot of trouble.

I'm getting warnings from EventYoshi:

```
Trace
    at addListener (events.js:239:17)
    at EventYoshi.on (/Users/Michael/Code/MagicMirror/node_modules/eventyoshi/lib/index.js:146:15)
    at EventYoshi.once (/Users/Michael/Code/MagicMirror/node_modules/eventyoshi/lib/index.js:170:8)
    at IconvLiteDecoderStream.Readable.pipe (_stream_readable.js:568:8)
    at self.fetchNews (/Users/Michael/Code/MagicMirror/modules/default/newsfeed/newsfetcher.js:49:76)
    at fetchNews (/Users/Michael/Code/MagicMirror/modules/default/newsfeed/fetcher.js:40:15)
    at .<anonymous> (/Users/Michael/Code/MagicMirror/modules/default/newsfeed/fetcher.js:58:4)
    at Timer.listOnTimeout (timers.js:92:15)
(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
```

The mentioned number of listeners (11) does not increase. So it's doesn't seem like a real issue. Maybe it's a good idea to increase the maxListeners?

**Comment by fent** [comment]
Can I see more of how this is used? What's in newsfetcher.js?

**Comment by MichMich** [comment]
Here you go: https://github.com/MichMich/MagicMirror/blob/v2-beta/modules/default/newsfeed/newsfetcher.js

**Comment by fent** [comment]
A brand new instance of FeedMe should be used for every request. I'm surprised it kinda works the way it currently is, since FeedMe assumes the document has ended and there's nothing more, after it finishes reading the first feed.

Also, you can set the `buffer` option to true, and use [done()](https://github.com/fent/feedme.js#parserdone) to get all the items at the end, just so you don't have to keep track yourself.

**Comment by MichMich** [comment]
Ok! Thans for the info. Consider it fixed. If I keep running into this problem, I'll reopen this issue.

**Comment by fent** [comment]
Sure.
